[workspace]
resolver = "2"
members = ["nql", "nql-ir", "nqlite", "nql-cli", "nql-server", "nql-mcp"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/devstroop/nqlite"
rust-version = "1.80"

[workspace.dependencies]
thiserror = "1"
serde = { version = "1", features = ["derive"] }

[profile.release]
lto = "thin"
codegen-units = 1